trigger:
- code_review

pr:
- code_review


variables:
- group: SONARCRED
- name: AgentImage
  value: "ubuntu-latest"
- name:  projectFolder
  value: '.'
- name: SecureFile
  value: ".env"



stages: 
- stage: 'Build_Stage' 
  displayName: 'Build' 
  jobs:
  - job: 'Build_Job' 
    displayName: 'Application Build' 
    pool:
      vmImage: $(AgentImage)
    steps:

      - task: DownloadSecureFile@1
        inputs:
          secureFile: '$(SecureFile)'
      
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Agent.TempDirectory)'
          contents: '**/$(SecureFile)'
          targetFolder: '$(projectFolder)'
          cleanTargetFolder: false

      - task: SonarQubePrepare@6
        inputs:
          SonarQube: 'sonarqube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: $(Projectkey)
          cliSources: '.'      

      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'
        displayName: 'Install Node.js'
  
      - script: |
          npm install --legacy-peer-deps
          npm run deploy
        displayName: 'npm install and deploy'
      
      - task: SonarQubeAnalyze@6
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'
      
      - task: SonarQubePublish@6
        inputs:
          pollingTimeoutSec: '300' 
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'out'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Files'
  
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact in drop'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'


- stage: 'UAT' 
  displayName: 'Deploy_in_UAT' 
  dependsOn: ['Build_Stage']
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI','Manual','BatchedCI'), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))
  jobs:
  - deployment: DeployToUAT 
    displayName: 'Deploy to UAT environment'
    variables:  
      Artifact: 'drop'
      AppType: 'Web App on Windows'
      WebApName: 'uat-ui-app'
      ResourceGroupNam: 'UAT_rg'
      packageForLinux: '$(System.DefaultWorkingDirectory)'
    pool:
      vmImage: $(AgentImage) 
    environment: 'UAT Environment'
    strategy:
      runOnce:
        deploy:
         steps:
           - task: DownloadPipelineArtifact@2
             displayName: 'Download artifacts in Agent Working Dir'
             inputs:
               artifact:  $(Artifact)
               path: $(System.DefaultWorkingDirectory)

           - task: AzureRmWebAppDeployment@4
             displayName: 'Azure App Service Deploy'
             inputs:
               ConnectionType: 'AzureRM' 
               appType: $(AppType) 
               azureSubscription: "SP"
               WebAppName: $(WebAppName)
               ResourceGroupName:  $(ResourceGroupName)
               packageForLinux: $(packageForLinux) 
  